[env:esp32dev]
; platform = espressif32@1.12.4  ; 这是一个非常关键的点！
; 在 PIO 中，platform 1.12.4 对应的是 Arduino Core 1.0.4~1.0.6 左右的版本
; 这是最接近你原本 IDE 环境的“时光机”版本。
; 因为air_ble.cpp里std::string v = c->getValue(); 在Core 3.里会编译失败
; platform = espressif32@3.5.0 ; 这是对应 Core 2.0.x 的版本，如果上面的不行再试这个
; 新NimBLE库需要Core 2.0以上，Core 3.x的版本可能会有兼容性问题，尤其是一些C++11特性的支持。所以可以强制C++17
; build_unflags = -std=gnu++11
; build_flags = 
;     -std=gnu++17
; 或者直接最新 board
platform = espressif32 @ 6.5.0  ; 或者直接用最新版 espressif32
; platform = espressif32      ; 这是自动最新版(Core 3.x)，建议注视掉，因为过几个月重新打开版本就变了
; 这是储存位置   C:\Users\Popst\.platformio   ，需要手动删除
; 8266的才140KB，32的几MB？！？
; 小貼士：packages 裡面的編譯器 才是大頭
; 建議：刪了舊的 platform，再跑 pio system prune。会删掉 没人用的 package 

; 左下角选择编译哪个项目时
; 建議永遠選帶 env: 開頭的那一個！
; 原因：如果你選了 Default，萬一哪天你改了 .ini 裡的 default_envs，或者你沒寫這行，PIO 可能會開始編譯專案裡所有的環境，這會讓你硬碟爆掉且編譯超久。
; 精確性：選 env:esp32dev 能保證你編譯的是「這份特定配置」。



; 换board的时候记得 pio run --target clean 或缩写  pio run -t clean 删除target后再 pio run（避免手动 build 一次）
;    
; 没用就手动删 .pio/build 文件夹，或者直接删除整个 .pio 文件夹（下次编译会重建）。不清理的话可能会有莫名其妙的编译错误。比如

; collect2.exe: error: ld returned 1 exit status
; *** [.pio\build\esp32dev\firmware.elf] Error 1


board = esp32dev
framework = arduino
; 分区表：固件已经达到2MB，需要huge_app.csv方案（放弃OTA回溯）。或使用ESP32 N8模块
board_build.partitions = huge_app.csv
; CPU频率
board_build.f_cpu = 240000000L  ; 240MHz
; 闪存配置
board_build.flash_mode = dio    ; 垃圾板子用QIO，NVS会失败。必须用DIO！
board_build.f_flash = 80000000  ; 如果还有问题，就降频到40MHz
; PSRAM禁用
board_build.flags = -DBOARD_HAS_PSRAM=0


upload_port = COM9 ;根据实际情况修改
upload_speed = 460800 ;上传速度大点无妨

monitor_speed = 115200  ; 和烧录无关，修改这里后，重启PIO的监视器就行。
;这就是为什么你保存ini的时候右下角PIO会更新
;你可以用VS CODE商店的 Serial Monitor，功能多，但
;为了配合 exception_decoder 抓崩溃信息，建议使用 PIO 自带的监视器。因为它集成了解码器。

; 启用异常解码器（代码崩了能看堆栈）
monitor_filters = esp32_exception_decoder, time, colorize ;time显示时间戳， colorize是彩色
;这是神器！ 当你的 ESP32 崩溃重启（Guru Meditation Error）时，串口会吐出一堆 16 进制的内存地址（Backtrace）
;在 Arduino IDE 里你需要复制这些地址去用工具查。
;在 PIO 里，加上这行，它会自动把这些地址翻译成代码行号！ 
;直接告诉你是在 xxx.cpp 的第 N 行出的问题，方便极了！



; 文件系统 (强制使用 LittleFS)
; board_build.filesystem = littlefs //失败了，PIO无论如何设置都以SPIFFS构建，而非LITTLEFS

; 库依赖：Async 库必须在这里声明，PIO 会自动下载
lib_deps =
    h2zero/NimBLE-Arduino @ ^2.2.3  ;

    ;如果你代码里用到了 LittleFS，旧版本核心可能需要手动包含这个兼容库
    ;SPIFFS 已经过时了（Deprecated）：Espressif 官方已经停止维护 SPIFFS。
    ;它不支持目录结构，且在大量文件写入时效率低，容易产生碎片。
    ;LittleFS：更快，支持真实目录，断电保护更好。既然是新项目迁移，绝对建议上 LittleFS。
    ; lorol/LittleFS_esp32 @ ^1.0.6    //失败了，PIO无论如何设置都以SPIFFS构建，而非LITTLEFS

    ;V3版本使用ESP自带的WebServer库，因为Async的库无法使用强制门户和DNS劫持
    ; https://github.com/me-no-dev/ESPAsyncWebServer.git
    ; https://github.com/me-no-dev/AsyncTCP.git
; 需要独立测试模块时，就注释其他模块的源文件，避免编译错误
; build_src_filter = +<*> -<web_config.cpp>

; Release版本需要关闭调试输出，防止串口阻塞无线传输
build_flags = 
    -D CORE_DEBUG_LEVEL=0  ;测试阶段可以设置为5，发布时建议设置为0或3。
    ; 串口速率取决于Serial.begin()
    -O2 ; 发布版本建议使用-O2优化，测试阶段可以使用-Og更利于调试。
    ;但是我没有JTAG调试器，所以就一直用的-O2，运行速度还更快
    ; -D CONFIG_LITTLEFS_FOR_IDF_3_2 ; 兼容旧版IDF的LittleFS定义
