; ═══════════════════════════════════════════════════════════════
;  PlatformIO 配置 — MAVLink UDP 透传 (ESP-IDF + 11b DSSS)
; ═══════════════════════════════════════════════════════════════
;
;  框架：ESP-IDF（不是 Arduino！）
;  目标：ESP32 (classic)，240MHz，DIO Flash
;
;  关键配置项通过 sdkconfig.defaults 注入 menuconfig，
;  PlatformIO 在首次编译时会自动合并到 sdkconfig.esp32dev

[env:esp32dev]
; platform = espressif32
platform = espressif32 @ 6.5.0 
board = esp32dev
framework = espidf

upload_port = COM9 ;根据实际情况修改
upload_speed = 512000 ;上传速度大点无妨

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

; 指定自定义 sdkconfig 默认值文件 ;默认就是sdkconfig.defaults，除非你改了名字
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults
; 或者指定多个 defaults 文件（按顺序合并，后面的覆盖前面的）
; board_build.cmake_extra_args =
;     -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.robust"

; 大部分无效，都得在 sdkconfig.defaults 里设置
; build_flags = 
;     -D CORE_DEBUG_LEVEL=0  ; Arduino 的宏，IDF 不认，需要在 sdkconfig.defaults 里设置 CONFIG_LOG_DEFAULT_LEVEL=0
;     -O2 ; 在 IDF 里通过 menuconfig 设置，不是 build_flags